### ISSUE TITLE
FTUE for Group page

### ISSUE THREAD

**Issue by kanej** [HiElleApp/web#92]
After creating a group, the user is taken to the group page. They should see an extra text section discussing `Invites`.

The rule for whether this FTUE section is display is:

1. Are you the owner of the group

The owner of the group will see it until they click close against it.

**Comment by AquiGorka** [comment]
Just to add an idea, this will look cool in Garfield.

**Comment by leshokunin** [comment]
Garfield is the best cat in the comic world.

**Comment by AquiGorka** [comment]
Yep, I agree, although Silvester was cool too

**Comment by leshokunin** [comment]
True, but speaking of Silvester, how cool was Stallone in Demolition Man?
